In [1]:
import pandas as pd

In [85]:
df = pd.read_csv("https://ddbj.nig.ac.jp/public/mirror_database/1000genomes/20131219.populations.tsv",sep="\t")

In [77]:
df.dropna(how="any",inplace=True)

In [79]:
df.head(100)

,Population Description,Population Code,Super Population,DNA from Blood,Offspring available from trios,Pilot Samples,Phase1 Samples,Final Phase Samples,Total
0,"Chinese Dai in Xishuangbanna, China",CDX,EAS,no,yes,0.0,0.0,99.0,99.0
1,"Han Chinese in Bejing, China",CHB,EAS,no,no,91.0,97.0,103.0,106.0
2,"Japanese in Tokyo, Japan",JPT,EAS,no,no,94.0,89.0,104.0,105.0
3,"Kinh in Ho Chi Minh City, Vietnam",KHV,EAS,yes,yes,0.0,0.0,101.0,101.0
4,"Southern Han Chinese, China",CHS,EAS,no,yes,0.0,100.0,108.0,112.0
5,Bengali in Bangladesh,BEB,SAS,no,yes,0.0,0.0,86.0,86.0
6,"Gujarati Indian in Houston,TX",GIH,SAS,no,yes,0.0,0.0,106.0,106.0
7,Indian Telugu in the UK,ITU,SAS,yes,yes,0.0,0.0,103.0,103.0
8,"Punjabi in Lahore,Pakistan",PJL,SAS,yes,yes,0.0,0.0,96.0,96.0
9,Sri Lankan Tamil in the UK,STU,SAS,yes,yes,0.0,0.0,103.0,103.0
10,African Ancestry in Southwest US,ASW,AFR,no,yes,0.0,61.0,66.0,66.0
11,African Caribbean in Barbados,ACB,AFR,yes,yes,0.0,0.0,96.0,96.0
12,Esan in Nigeria,ESN,AFR,no,yes,0.0,0.0,99.0,99.0
13,"Gambian in Western Division, The Gambia",GWD,AFR,no,yes,0.0,0.0,113.0,113.0
14,"Luhya in Webuye, Kenya",LWK,AFR,no,yes,102.0,97.0,101.0,116.0
15,Mende in Sierra Leone,MSL,AFR,no,yes,0.0,0.0,85.0,85.0
16,"Yoruba in Ibadan, Nigeria",YRI,AFR,no,yes,106.0,88.0,109.0,116.0
17,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
18,Finnish in Finland,FIN,EUR,no,no,0.0,93.0,99.0,100.0
19,Iberian populations in Spain,IBS,EUR,no,yes,0.0,14.0,107.0,107.0
20,Toscani in Italy,TSI,EUR,no,no,66.0,98.0,108.0,110.0
21,Utah residents with Northern and Western Europ...,CEU,EUR,no,yes,94.0,85.0,99.0,103.0
22,"Colombian in Medellin, Colombia",CLM,AMR,no,yes,0.0,60.0,94.0,95.0
23,"Mexican Ancestry in Los Angeles, California",MXL,AMR,no,yes,0.0,66.0,67.0,69.0
24,"Peruvian in Lima, Peru",PEL,AMR,yes,yes,0.0,0.0,86.0,86.0
25,Puerto Rican in Puerto Rico,PUR,AMR,yes,yes,0.0,55.0,105.0,105.0

In [84]:
df.columns

Index(['Population Description', 'Population Code', 'Super Population',
       'DNA from Blood', 'Offspring available from trios', 'Pilot Samples',
       'Phase1 Samples', 'Final Phase Samples', 'Total'],
      dtype='object')

In [82]:
df['Pilot Samples'].astype('int').mean()

21.26923076923077

In [83]:
df['Phase1 Samples'].astype('int').mean()

42.0

In [67]:
df['Pilot Samples'].fillna(0).astype('int').sum()

1106

In [43]:
df[['Phase1 Samples','Final Phase Samples']].sum()

Phase1 Samples         2184.0
Final Phase Samples    5070.0
dtype: float64

In [33]:
import logging

In [34]:
logging.basicConfig(filename="analysis_app.log",format='%(asctime)s %(message)s',filemode='a')

In [35]:
# logger = logging.getLogger()

In [36]:
logger.log(10,"This is test log message for lvl 10, debug mode")

In [37]:
logger.debug("This test log for debug mode",exc_info=True)

In [87]:
df.head(100)

,Population Description,Population Code,Super Population,DNA from Blood,Offspring available from trios,Pilot Samples,Phase1 Samples,Final Phase Samples,Total
0,"Chinese Dai in Xishuangbanna, China",CDX,EAS,no,yes,0.0,0.0,99.0,99.0
1,"Han Chinese in Bejing, China",CHB,EAS,no,no,91.0,97.0,103.0,106.0
2,"Japanese in Tokyo, Japan",JPT,EAS,no,no,94.0,89.0,104.0,105.0
3,"Kinh in Ho Chi Minh City, Vietnam",KHV,EAS,yes,yes,0.0,0.0,101.0,101.0
4,"Southern Han Chinese, China",CHS,EAS,no,yes,0.0,100.0,108.0,112.0
5,Bengali in Bangladesh,BEB,SAS,no,yes,0.0,0.0,86.0,86.0
6,"Gujarati Indian in Houston,TX",GIH,SAS,no,yes,0.0,0.0,106.0,106.0
7,Indian Telugu in the UK,ITU,SAS,yes,yes,0.0,0.0,103.0,103.0
8,"Punjabi in Lahore,Pakistan",PJL,SAS,yes,yes,0.0,0.0,96.0,96.0
9,Sri Lankan Tamil in the UK,STU,SAS,yes,yes,0.0,0.0,103.0,103.0
10,African Ancestry in Southwest US,ASW,AFR,no,yes,0.0,61.0,66.0,66.0
11,African Caribbean in Barbados,ACB,AFR,yes,yes,0.0,0.0,96.0,96.0
12,Esan in Nigeria,ESN,AFR,no,yes,0.0,0.0,99.0,99.0
13,"Gambian in Western Division, The Gambia",GWD,AFR,no,yes,0.0,0.0,113.0,113.0
14,"Luhya in Webuye, Kenya",LWK,AFR,no,yes,102.0,97.0,101.0,116.0
15,Mende in Sierra Leone,MSL,AFR,no,yes,0.0,0.0,85.0,85.0
16,"Yoruba in Ibadan, Nigeria",YRI,AFR,no,yes,106.0,88.0,109.0,116.0
17,British in England and Scotland,GBR,EUR,no,yes,0.0,89.0,92.0,94.0
18,Finnish in Finland,FIN,EUR,no,no,0.0,93.0,99.0,100.0
19,Iberian populations in Spain,IBS,EUR,no,yes,0.0,14.0,107.0,107.0
20,Toscani in Italy,TSI,EUR,no,no,66.0,98.0,108.0,110.0
21,Utah residents with Northern and Western Europ...,CEU,EUR,no,yes,94.0,85.0,99.0,103.0
22,"Colombian in Medellin, Colombia",CLM,AMR,no,yes,0.0,60.0,94.0,95.0
23,"Mexican Ancestry in Los Angeles, California",MXL,AMR,no,yes,0.0,66.0,67.0,69.0
24,"Peruvian in Lima, Peru",PEL,AMR,yes,yes,0.0,0.0,86.0,86.0
25,Puerto Rican in Puerto Rico,PUR,AMR,yes,yes,0.0,55.0,105.0,105.0
26,Total,NaN,NaN,NaN,NaN,553.0,1092.0,2535.0,2577.0
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [101]:
import pycountry

In [91]:
list_alpha_2 = [i.alpha_2 for i in list(pycountry.countries)]
list_alpha_3 = [i.alpha_3 for i in list(pycountry.countries)]

In [96]:
pycountry.countries.get(alpha_3="PEL").name

AttributeError: 'NoneType' object has no attribute 'name'

In [99]:
df['Population Code'].apply(lambda x: pycountry.countries.get(alpha_3=x))

LookupError:

In [104]:
test = pycountry.countries.get(alpha_3="PEL")